export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const RETRIEVE_TRANSACTION = "RETRIEVE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTIONL";
export const DELETE_ALL_TRANSACTION = "DELETE_ALL_TRANSACTION";